config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    constraints subdomain: 'www' do
      get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
    end
  end

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.add_routes do
    resources :babes

    get '/build_your_babe' => 'babes#access_concierge'
    get '/my_babes_package_list/:id' => 'taxons#my_babes_package_list', as: 'my_babes_package_list'
    get '/' => 'home#concierge_page'

    get '/about' => 'home#about'
    get '/how_the_wishlist_works' => 'home#how_the_wishlist_works'
    get '/ourstory' => 'home#ourstory'
    get '/returns_and_exchanges' => 'home#returns_and_exchanges'
    get '/privacy_policy' => 'home#privacy_policy'
    get '/terms_of_use' => 'home#terms_of_use'
    get '/sizing' => 'home#sizing'
    get '/csrf_meta_tags' => 'home#csrf_meta_tags'

    match '/admin/reports/abandoned_carts' => 'admin/reports#abandoned_carts',  :via  => [:get, :post],
          :as   => 'abandoned_carts_admin_reports'

  end

end

app/models/spree/babe.rb
module Spree
  class Babe < ActiveRecord::Base
    
    CUP_SIZES = [ "A", "B", "C", "D", "DD", "F" ]
    BAND_SIZES = [ "30", "32", "34", "36", "38" ]
    BOTTOMS_SIZES = [ "XS", "S", "M", "L", "XL" ]
    #BOTTOMS_SIZES = [ "XSmall", "Small", "Medium", "Large", "XLarge" ]
    
    belongs_to :body_type

    def my_body_type
      self.body_type.name
    end

    def display_name_babe
      self.name == '' ? 'Your Babe' : self.name
    end

    def display_name_lady
      self.name == '' ? 'Your Lady' : self.name
    end

    def set_personality_from_trait_array(chosen_traits)
      self.vixen_value = 0
      self.flirt_value = 0
      self.romantic_value = 0
      self.sophisticate_value = 0
      chosen_traits.each do |t|
        self.vixen_value += t.vixen_value
        self.flirt_value += t.flirt_value
        self.romantic_value += t.romantic_value
        self.sophisticate_value += t.sophisticate_value

      end
      self.vixen_value = (self.vixen_value / chosen_traits.length).round(2)
      self.flirt_value = (self.flirt_value / chosen_traits.length).round(2)
      self.romantic_value = (self.romantic_value / chosen_traits.length).round(2)
      self.sophisticate_value = (self.sophisticate_value / chosen_traits.length).round(2)
      if self.personality[0][1] == self.personality[1][1]
        primary_personality_values = []
        secondary_personality_values = []
        chosen_traits.each do |t|
          primary_personality_values.push(t[personality[0][0]])
          secondary_personality_values.push(t[personality[1][0]])
        end
        primary_personality_values = primary_personality_values.sort.reverse
        secondary_personality_values = secondary_personality_values.sort.reverse
        primary_total_of_top_n = 0
        secondary_total_of_top_n = 0
        for i in 0..(chosen_traits.size-2)
          primary_total_of_top_n = primary_total_of_top_n + primary_personality_values[i]
          secondary_total_of_top_n = secondary_total_of_top_n + secondary_personality_values[i]
        end

        if primary_total_of_top_n > secondary_total_of_top_n
          self[personality[0][0]] = personality[0][1] + 0.1
        else
          self[personality[1][0]] = personality[1][1] + 0.1
        end
      end
    end

    def words(trait)
      if trait.downcase == 'vixen_value'
        return 'sassy'
      elsif trait.downcase == 'flirt_value'
        return 'flirty'
      elsif trait.downcase == 'sophisticate_value'
        return 'sophisticated'
      elsif trait.downcase == 'romantic_value'
        return 'romantic'
      end
    end

    def personality_statement
      "She's really #{self.words(self.personality[0][0])}, and pretty #{self.words(self.personality[1][0])}."
    end

    def personality_statment_with_brevity
      "Really #{self.words(self.personality[0][0])}, and pretty #{self.words(self.personality[1][0])}."
    end

    def personality
      personality = Hash.new
      personality['vixen_value'] = self.vixen_value
      personality['flirt_value'] = self.flirt_value
      personality['sophisticate_value'] = self.sophisticate_value
      personality['romantic_value'] = self.romantic_value
      personality.sort_by {|_key, value| value}.reverse.first 2
    end

    def bra_size
      "#{self.band}#{self.cup}".upcase
    end

    def size_value_for_size_option_type_name(size_type_name)
      if size_type_name.downcase == 'named sizes'
        return self.bottoms
      elsif size_type_name.downcase == 'bra sizes'
        return self.bra_size
      elsif size_type_name.downcase == 'number sizes'
        return self.number_size
      elsif size_type_name.downcase == 'one size'
        return 'one size'
      end
    end

    private

    def initialize(attributes={})
      super
      self.vixen_value ||= 0
      self.flirt_value ||= 0
      self.romantic_value ||= 0
      self.sophisticate_value ||= 0
    end

  end
end

app/models/spree/babe_product_search_failure.rb
module Spree
  class BabeProductSearchFailure < ActiveRecord::Base

  end
end

app/models/spree/babe_trait_type.rb
module Spree
  class BabeTraitType < ActiveRecord::Base
    has_many :spree_babe_trait_values, :class_name => 'Spree::BabeTraitValue'
    validates_presence_of :name
  end
end

app/models/spree/babe_trait_value.rb
module Spree
  class BabeTraitValue < ActiveRecord::Base
    belongs_to :spree_babe_trait_type, :class_name => 'Spree::BabeTraitType'

    def load_personality_traits(vixen,sophisticate,flirt,romantic)
      self.vixen_value = vixen
      self.sophisticate_value = sophisticate
      self.flirt_value = flirt
      self.romantic_value = romantic
      self.save
    end

  end
end

app/models/spree/body_type.rb
module Spree
  class BodyType < ActiveRecord::Base
    validates_presence_of :name


  end
end

app/models/spree/captcha_configuration.rb
class Spree::CaptchaConfiguration < Spree::Preferences::Configuration
  THEMES = %w(red white blackglass clean custom)

  # These keys works for localhost.
  preference :private_key, :string,  default: '6LeygQ0TAAAAAHIv8a-uBmdfpmkO81n5YgBtKb6A'
  preference :public_key,  :string,  default: '6LeygQ0TAAAAAB3ayjq7hPzBeAEh7k0t_kFmeXPr'
  preference :theme,       :string,  default: 'red'
  preference :use_captcha, :boolean, default: true

  # can also run these commands from the rails console
  #Spree::Captcha::Config.public_key = '6LeygQ0TAAAAAB3ayjq7hPzBeAEh7k0t_kFmeXPr'
  #Spree::Captcha::Config.private_key = '6LeygQ0TAAAAAHIv8a-uBmdfpmkO81n5YgBtKb6A'

end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do


  def isSizeOptionType?
    self.presentation.downcase == 'size'
  end



end

app/controllers/spree/admin/reports_controller_decorator.rb
module Spree
  module Admin
    ReportsController.class_eval do

      def abandoned_carts

        params[:q] = {} unless params[:q]

        if params[:q][:created_at_gt].blank?
          params[:q][:created_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end

        if params[:q] && !params[:q][:completed_at_lt].blank?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        end

        params[:q][:s] ||= "created_at desc"

        @search = Order.where.not(state: 'complete').ransack(params[:q])

        @total_abandoned_carts = @search.result
        @total_no_user = @total_abandoned_carts.where(state: 'cart')
        @total_no_address =  @total_abandoned_carts.where(state: 'address')
        @total_no_delivery =  @total_abandoned_carts.where(state: 'delivery')
        @total_no_payment = @total_abandoned_carts.where(state: 'payment')
        @total_no_confirm = @total_abandoned_carts.where(state: 'confirm')
      end

      def sales_total
        params[:q] = {} unless params[:q]

        if params[:q][:completed_at_gt].blank?
          params[:q][:completed_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:completed_at_gt] = Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end

        if params[:q] && !params[:q][:completed_at_lt].blank?
          params[:q][:completed_at_lt] = Time.zone.parse(params[:q][:completed_at_lt]).end_of_day rescue ""
        end

        params[:q][:s] ||= "completed_at desc"

        @search = Order.complete.ransack(params[:q])
        @orders = @search.result

        @totals = {}
        # set defaults
        @totals['USD'] = {:item_total=>0,:sales_total=>0,:adjustment_total=>0}

        @cost = 0
        @taxes = Hash.new(0)
        @shipping = 0
        @orders.each do |order|
          @totals[order.currency] = { :item_total => ::Money.new(0, order.currency),:cost_total => ::Money.new(0, order.currency),:shipping_total => ::Money.new(0, order.currency), :adjustment_total => ::Money.new(0, order.currency), :sales_total => ::Money.new(0, order.currency) } unless @totals[order.currency]
          @totals[order.currency][:item_total] += order.display_item_total.money
          @totals[order.currency][:adjustment_total] += order.display_adjustment_total.money
          @shipping += order.shipment_total
          Spree::Adjustment.where(:order_id => order.id).each do |adjustment|
            @taxes[adjustment.label.to_s] += adjustment.amount
          end
          order.line_items.each do |li|
            @cost += (li.product.master.cost_price*li.quantity) if li.product.master.cost_price
          end
          #@cost += order.line_items.inject(0) { |cost, li| cost + (li.variant.cost_price.to_f)*li.quantity }
          @totals[order.currency][:sales_total] += order.display_total.money
        end
        # Rails.logger.debug("HERE I AM: #{@taxes.inspect}")
        # Rails.logger.debug("totals: #{@totals.inspect}")
      end
    end
  end
end

app/controllers/spree/babes_controller.rb
module Spree
  class BabesController < Spree::StoreController

    before_action :set_babe, only: [:show, :edit, :update, :destroy]


    # need to figure out how to get the session token onto the form for submission if the page is cached
    #caches_page :new

    def index

      #@babes = Babe.where("spree_user_id = #{spree_current_user.id} OR guest_token = '#{cookies.signed[:guest_token]}'")
      # babe_params = {}
      # babe_params['spree_user_id'] = spree_current_user.id if spree_current_user
      # babe_params['guest_token'] = cookies.signed[:guest_token] if cookies.signed[:guest_token].present?
      # @babes = Babe.where(babe_params).where_values.reduce(:or)

      if spree_current_user && !cookies.signed[:guest_token].present?
        @babes = Babe.where(:spree_user_id => spree_current_user.id)
      elsif !spree_current_user && cookies.signed[:guest_token].present?
        @babes = Babe.where(:guest_token => cookies.signed[:guest_token])
      elsif spree_current_user && cookies.signed[:guest_token].present?
        @babes = Babe.where("spree_user_id = #{spree_current_user.id} OR guest_token = '#{cookies.signed[:guest_token]}'")
      else
        redirect_to new_babe_path
      end

      if spree_current_user && spree_current_user.id == 1
        @babes = @babes.last(5)
      end
      @babes
    end

    def current_guest_token_has_babes?
      if cookies.signed[:guest_token].present?
        return (Spree::Babe.where("guest_token = '#{cookies.signed[:guest_token]}'").count > 0)
      end
    end

    def access_concierge
      if (spree_current_user && spree_current_user.has_babes?) || current_guest_token_has_babes?
        redirect_to babes_path
      else
        redirect_to new_babe_path
      end
    end

    def new
      @babe = Babe.new
      @active_traits = Spree::BabeTraitType.where("active = ?",true)
    end

    def create
      babe_personality_traits = []
      for i in 1..params[:number_of_active_traits].to_i
        babe_personality_traits.push(Spree::BabeTraitValue.find(params["babe_trait_#{i}"]))
      end
      @babe = Spree::Babe.new(babe_params)
      setBottomSize(@babe.bottoms);
      @babe.spree_user_id = spree_current_user.id if spree_current_user
      @babe.set_personality_from_trait_array(babe_personality_traits) if babe_personality_traits.size > 0
      @babe.guest_token = cookies.signed[:guest_token] if cookies.signed[:guest_token].present?
      respond_to do |format|
        if @babe.save
          format.html {redirect_to my_babes_package_list_path(@babe)}
        else
          format.html { render :new }
        end
      end
    end

    

    def destroy
      if @babe.id = session[:babe_id]
        session.delete(:babe_id)
      end
      @babe.destroy
      respond_to do |format|
        format.html { redirect_to build_your_babe_path, notice: 'Your babe was successfully deleted. Hopefully you will find plenty of new distractions.' }
      end
    end

    private

    def set_babe
      @babe = Babe.find(params[:id])
    end
    
    def setBottomSize(bottoms)
      bottom_hash = {'XS'=>'XSmall','S'=>'Small','M'=>'Medium','L'=>'Large','XL'=>'XLarge'}
      number_size_hash = {'XSmall'=>'1','Small'=>'2','Medium'=>'3','Large'=>'4','XLarge'=>'5'}
      if bottom_hash[bottoms]
        @babe.bottoms = bottom_hash[bottoms]
      end
      @babe.number_size = number_size_hash[@babe.bottoms]
    end

    def babe_params
      params.require(:babe).permit(:spree_user_id, :body_type_id, :name, :height, :band, :cup, :bottoms, :number_size, :vixen_value, :romantic_value, :flirt_value, :sophisticate_value, :guest_email)
    end


  end
end

app/controllers/spree/home_controller_decorator.rb
module Spree
  HomeController.class_eval do

    caches_page :concierge_page, :about, :ourstory, :privacy_policy, :returns_and_exchanges, :terms_of_use, :sizing
    
    def concierge_page
    end

    def about
    end

    def ourstory
    end

    def privacy_policy
    end

    def returns_and_exchanges
    end

    def terms_of_use
    end

    def sizing
    end

    def how_the_wishlist_works
    end

    def csrf_meta_tags
      render layout: false
    end

  end
end

app/controllers/spree/omniauth_callbacks_controller_decorator.rb
module Spree
  OmniauthCallbacksController.class_eval do

    after_action :set_auth_cookie, only: [:facebook]
    after_action :assign_babe, only: [:facebook]

  end
end

app/controllers/spree/orders_controller_decorator.rb
module Spree
  OrdersController.class_eval do

    before_action :set_redirect_back, only: [:populate,:populate_from_package]

    def set_redirect_back
      session["spree_user_return_to"] = :back
    end

    def populate_from_package
      # we'll store the array of varient id's in the varient id so it will pass validation
      # varients = params[:varient_id];
      order    = current_order(create_order_if_necessary: true)
      options  = {}

      begin
        highest_index_of_products = params['product_count'].to_i - 1
        Rails.logger.debug ("number of products: #{highest_index_of_products}")
        for i in 0..highest_index_of_products
          variant  = Spree::Variant.find(params["variant_id_#{i}"])
          quantity = params["quantity_#{i}"]
          babe_id = params["babe_id"] ? params["babe_id"] : nil
          order.contents.add(variant, quantity, options, babe_id)
        end
      rescue ActiveRecord::RecordInvalid => e
        error = e.record.errors.full_messages.join(", ")
      end

      if error
        flash[:error] = error
        redirect_back_or_default(spree.root_path)
      else
        respond_with(order) do |format|
          format.html { redirect_to cart_path }
        end
      end
    end

  end
end

app/controllers/spree/products_controller_decorator.rb
module Spree
  ProductsController.class_eval do

    def show_package
      @taxon = Taxon.friendly.find(params[:id])
      return unless @taxon
      @searcher = build_searcher(params.merge(taxon: @taxon.id, include_images: true))
      @products = @searcher.retrieve_products.sort_by { |p| p.product_size_type.name} # makes sure bras are always displayed first
      package_price = 0.00
      @products.each do |p|
        package_price = package_price + p.price_in(current_currency).amount
      end
      @taxon.package_price = sprintf('%.0f', package_price)
      @pre_selected_sizes = []
      if session.key?(:babe_id)
        babe = Spree::Babe.find(session[:babe_id])
        @products.each_with_index do |product,index|
          size = Spree::Variant.size_matching_in_stock_option_value_for_babe(product.id,babe)
          @pre_selected_sizes.push(index.to_s+'-'+size)
        end
      end
    end

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products.includes(:option_types)
      @products = @products.includes(:option_types).where("spree_products.show_in_main_search" => true).order('priority asc')
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    def show
      @variants = @product.variants_including_master.active(current_currency).includes([:option_values, :images])
      @product_properties = @product.product_properties.includes(:property)
      @taxon = Spree::Taxon.find(params[:taxon_id]) if params[:taxon_id]
      @additional_products = load_additional_products
    end

    def load_additional_products
      additional_products = []
      @product.taxons.each do |taxon|
        if taxon.is_package_node
          taxon.products.each do |taxon_product|
            if taxon_product.id != @product.id
              additional_products.push(taxon_product);
            end
          end
        end
      end
      return additional_products
    end

  end
end

app/views/spree/wishlists/_mail_to_friend.text.erb
<%= mail.recipient_name %>,
<% Rails.logger.debug @object.inspect %>
<%= Spree.t(:take_a_look_at_my_wishlist) %>

  * <%= @object.name %>

<% unless mail.message.blank? -%>
<%= mail.message %>
<% end -%>

<%= mail.sender_name %>

<%= Spree.t(:click_link_to_view_wishlist, name: @object.name) %>
<%= wishlist_url(@object) %>

app/views/spree/wishlists/show.html.erb
<div id="wishlist_header" class="row">
  <h1><%= @wishlist.name %></h1>
  <% if @wishlist.user == spree_current_user %>
    <div id="manage_wishlist_links">
      <%= link_to Spree.t(:edit_wishlist), edit_wishlist_path(@wishlist), class: 'button' %>
    </div>
    <div><%= render partial: 'accessibility' %></div>
  <% end -%>
</div>
<table id="wishlist" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th><%= Spree.t(:wishlist_actions) %></th>
      <th><%= Spree.t(:item_view) %></th>
      <th><%= Spree.t(:item_description) %></th>
      <th><%= Spree.t(:availability) %></th>
      <th><%= Spree.t(:date_added) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:quantity) %></th>
      <th><%= Spree.t(:total) %></th>
    </tr>
  </thead>
  <tbody id="line_items">
  <% if @wishlist.wished_products.size > 0 %>
    <% @wishlist.wished_products.each do |wish|
        variant = wish.variant
        product = variant.product %>
    <tr class="<%= cycle('', 'alt') %>">
    <% if @wishlist.user == spree_current_user %>
      <td>
        <p><%= link_to Spree.t(:remove_from_wishlist), wish, method: :delete, class: 'btn btn-danger' %></p>
        <%= form_for :order, url: populate_orders_url do |f| %>
          <%= hidden_field_tag 'variant_id', variant.id, size: 3 %>
          <%= Spree.t(:quantity) %>
          <%= number_field_tag 'quantity', wish.quantity, size: 3 %>
          <%= link_to Spree.t(:add_to_cart), '#', onclick: '$(this).parent().submit(); return false;', class: 'btn btn-success' %>
        <% end %>
        <% if spree_current_user.wishlists.count > 1 %>
          <%= Spree.t(:move_to_another_wishlist) %>:
          <%= form_for wish do |f| %>
            <%= f.select :wishlist_id, spree_current_user.wishlists.map{|wl| [wl.name, wl.id]} %>
            <%= f.submit Spree.t(:move), class: 'btn btn-default' %>
          <% end %>
        <% end %>
        <br />
      </td>
    <% else %>
      <td>
        <% if variant.can_supply? %>
          <%= form_for :order, url: populate_orders_url do |f| %>
            <%= hidden_field_tag 'variant_id', variant.id, size: 3 %>
            <%= Spree.t(:quantity) %>
            <%= number_field_tag 'quantity', wish.quantity, size: 3 %>
            <%= link_to Spree.t(:add_to_cart), '#', onclick: '$(this).parent().submit(); return false; ', class: 'btn btn-success' %>
          <% end %>
        <% else %>
          OUT OF STOCK
        <% end %>
      </td>
    <% end -%>
      <td>
        <% if variant.images.length == 0 %>
          <%= small_image(variant.product) %>
        <% else %>
          <%= image_tag variant.images.first.attachment.url(:small) %>
        <% end %>
      </td>
      <td>
        <h4><%= link_to product.name, product %></h4>
        <p><%= variant_options variant %></p>
        <%= truncate(strip_tags(product.description), length: 100, omission: '...') %>
      </td>
      <td>
        <%= variant.can_supply? ? Spree.t(:in_stock) : Spree.t(:out_of_stock) %>
      </td>
      <td>
        <%= wish.created_at.strftime '%m/%d/%Y' %>
      </td>
      <td>
        <%= display_price(variant) %>
      </td>
      <% if @wishlist.user == spree_current_user %>
        <td>
          <%= form_for wish do |f| %>
            <%= f.number_field :quantity %>
            <%= f.submit Spree.t('actions.save'), class: 'btn btn-info '  %>
          <% end %>
        </td>
      <% else %>
        <td>
          <%= wish.quantity %>
        </td>
      <% end %>
      <td>
        <%= wish.display_total %>
      </td>
    </tr>
    <% end -%>
  <% else -%>
    <tr>
      <td colspan="6"><%= Spree.t(:your_wishlist_is_empty) %></td>
    </tr>
  <% end -%>
  </tbody>
</table>
<div class="footer_links" data-hook="wishlist_footer_links">
<% if @wishlist.user == spree_current_user %>
  <%#= link_to Spree.t(:create_new_wishlist), new_wishlist_path, class: 'btn btn-default' %>
  <%= link_to Spree.t('email_to_friend.send_to_friend'), email_to_friend_url('wishlist', @wishlist), class: 'btn btn-default' %>&nbsp;&nbsp;
<% end -%>
<%= link_to Spree.t(:continue_shopping), products_path, class: 'btn btn-default' %>
</div>